### PR TITLE
Pushing news reporter module

### PR DESCRIPTION
**Pull request by aimran1**

### CODE REVIEW

**Review by jjames003 — APPROVED** [review]
This looks good to me!

**Comment by ej0306** [comment]
Does, this work on the latest version of python? - I'm trying to run it with python 3.10 and I'm getting the error of no module found.

**Comment by erchardsamoh** [comment]
When I run the unit test (test_reporter.py) -- it's giving me a "TypeError: expected string or bytes-like object". Not sure what that means, but I saw that the test worked during our meeting so I'm not sure what's happening on my end.

**Comment by stefantan18** [comment]
> Does, this work on the latest version of python? - I'm trying to run it with python 3.10 and I'm getting the error of no module found.

Did you pip install the module?

**Comment by stefantan18** [comment]
> When I run the unit test (test_reporter.py) -- it's giving me a "TypeError: expected string or bytes-like object". Not sure what that means, but I saw that the test worked during our meeting so I'm not sure what's happening on my end.

I get a similar error as Erchard. Do you what's the cause of this @aimran1?

**Comment by aimran1** [comment]
> > When I run the unit test (test_reporter.py) -- it's giving me a "TypeError: expected string or bytes-like object". Not sure what that means, but I saw that the test worked during our meeting so I'm not sure what's happening on my end.
> 
> I get a similar error as Erchard. Do you what's the cause of this @aimran1? I'm also assuming it works on your end.

This is likely an error with the assert functions not receiving the correct parameters. Not entirely sure why it isn't working on your machines, but I will try to figure it out. For now though, the pytest isn't necessary for integration so you should still be able to work with the reporter module.

**Comment by aimran1** [comment]
> .

Not s

> Does, this work on the latest version of python? - I'm trying to run it with python 3.10 and I'm getting the error of no module found.

My machine was running it on Python 3.9 but I do not think that is the issue. Most likely the path the module is being imported from is incorrect.

**Comment by erchardsamoh** [comment]
> When I run the unit test (test_reporter.py) -- it's giving me a "TypeError: expected string or bytes-like object". Not sure what that means, but I saw that the test worked during our meeting so I'm not sure what's happening on my end.

After getting the API key and putting that in reporter.py , the test_reporter.py now works properly.

**Comment by stefantan18** [comment]
> 

Oh ok yea that makes sense. I had a feeling that it was something minor causing the issue.

**Pull request closed without merging**
