### PR TITLE
Merging changes made from ui-design-testing to static fixes

### PR DESCRIPTION
**Pull request by jjames003**
Fixed user navigation to login, register, and preference pages. Added testing modules to see button functionality. Connected user apps, added news apis, created user directory for user templates.

### CODE REVIEW

**Comment by stefantan18** [comment]
There seems to be conflicts that must be resolved before merging.

**Comment by erchardsamoh** [comment]
> There seems to be conflicts that must be resolved before merging.

yup, its due to my staticfixes branch originally stemming from the updated main branch. for example, i for some reason decided to name the registration.html file as register.html in my static branch. 

anyways, this shouldn't be too hard to fix.

**Comment by stefantan18** [comment]
> > There seems to be conflicts that must be resolved before merging.
> 
> yup, its due to my staticfixes branch originally stemming from the updated main branch. for example, i for some reason decided to name the registration.html file as register.html in my static branch.
> 
> anyways, this shouldn't be too hard to fix.

Got it, as long as we know what the cause of the conflict is and how to fix it we should be good.

**Comment by aimran1** [comment]
Having issues running the current branch locally. Getting "ModuleNotFoundError: No module named 'crispy_forms'"

**Comment by Breathing-ls-Fun** [comment]
> Having issues running the current branch locally. Getting "ModuleNotFoundError: No module named 'crispy_forms'"

you have to install the crispy forms package in your virtual environmentby doing pip install django-crispy-forms

**Comment by jjames003** [comment]
Resolved the conflicts in all the files. I accepted my incoming changes to keep everything up to date. One more person should review the resolved changes, but if no conflicts are still seen, it is ready to merge.

**Comment by stefantan18** [comment]
> Resolved the conflicts in all the files. I accepted my incoming changes to keep everything up to date. One more person should review the resolved changes, but if no conflicts are still seen, it is ready to merge.

Merged. Let me know if there are any conflicts or issues so I can revert if needed.

**Pull request merged**
