### PR TITLE
Reporter

### PR DESCRIPTION
**Pull request by aimran1**
Created weatherman object. Currently able to retrieve and provide information on the current weather.

### CODE REVIEW

**Review by thouship — APPROVED** [review]
Looks good to me

**Comment by erchardsamoh** [comment]
Yup looks good as well, we just need to make sure the pyowm module is in our requirements.txt and the API key is provided somewhere so we don't run into the same problems from the NewsAPI.

**Review by stefantan18 — APPROVED** [review]
Everything looks good. Merge approved.

**Comment by aimran1** [comment]
Will merge with frontend and test integration before merging with main.

**Pull request closed without merging**
