### PR TITLE
fixed spacing between genres + added more unit tests + other  minor cleanups

### PR DESCRIPTION
**Pull request by erchardsamoh**
fixed the spacing issue as reported by Joel in the previous PR. did so by making the list section display as a flexbox and editing gap value. initially, it was not in any sort of display type.

also, i made edits to the home page in terms of weatherbox spacing, adding a third article card and editing its layouts.

### CODE REVIEW

**Comment by stefantan18** [comment]
Got it. Looks good.

**Review by ej0306 — APPROVED** [review]
Everything looks good.

**Comment by stefantan18** [comment]
Oh there seems to be a merge conflict now for some reason?

**Comment by erchardsamoh** [comment]
> Oh there seems to be a merge conflict now for some reason?

It's because Joel had pushed some other new changes into the testing branch before this could get fully merged. Joel said he was gonna look into it today to resolve the conflicts.

**Pull request merged**
