### PR TITLE
Weatherman Update: Daily Forecast

### PR DESCRIPTION
**Pull request by aimran1**
Added daily forecast for 5 days for weatherman and some error handling for invalid location entry. Added unit tests for weatherman.

### CODE REVIEW

**Review by stefantan18 — APPROVED** [review]
The changes looks good.

**Comment by erchardsamoh** [comment]
agreed, everything looks fine here.

**Review by thouship — APPROVED** [review]
Looks good to go.

**Comment by jjames003** [comment]
The changes are working without any errors popping up on my local machine. Looks good to me and is ready to merge btw.

**Comment by Breathing-ls-Fun** [comment]
I'll go ahead and merge this then.

**Pull request merged**
